### PR TITLE
Add ref for Concise Bounded Description

### PR DESCRIPTION
**Pull request by afs**

### CODE REVIEW

**Comment by gkellogg** [comment]
Are there general enough that they should go into the spec ref repository? Or, unlikely to be cited by anything else? If so, I can do a PR against specref and they’ll automatically resolve by respec.

**Comment by afs** [comment]
CBD yes, Multisets no 

What is the policy on plain hrefs (this is to wikipedia)?

**Comment by gkellogg** [comment]
> CBD yes, Multisets no
> 
> What is the policy on plain hrefs (this is to wikipedia)?

An informative reference should be fine. I think I’ve seen some that reference a specific state of a wiki page to guard against future changes.

**Comment by gkellogg** [comment]
I can create a PR to add CBD to specref.

**Review by gkellogg — APPROVED** [review]

**Comment by gkellogg** [comment]
In rdf-canon, there are some wiki entries as plain links: e.g.:

    <p>To understand the basics in this specification you must be familiar with
      basic RDF concepts [[!RDF11-CONCEPTS]]. A working knowledge of
      <a href="https://en.wikipedia.org/wiki/Graph_theory">graph theory</a> and
      <a href="https://en.wikipedia.org/wiki/Graph_isomorphism">graph isomorphism</a>
      is also recommended.</p>

This might be an alternative to a bibliographic citation.

**Pull request merged**
